export enum QueryKeys {
  // user related
  GET_USER = "GET_USER",
  GET_USER_BY_ID = "GET_USER_BY_ID",
  GET_USERS = "GET_USERS",
  LOGIN_USER = "LOGIN_USER",
  REGISTER_USER = "REGISTER_USER",
  UPDATE_USER = "UPDATE_USER",
  // book related
  GET_BOOK = "GET_BOOK",
  UPDATE_BOOK_QUANTITY = "UPDATE_BOOK_QUANTITY",
  GET_ALL_BOOKS = "GET_ALL_BOOKS",
  GET_ALL_BOOKS_FROM_BOOK_DETAILS = "GET_ALL_BOOKS_FROM_BOOK_DETAILS",
  // checkout related
  CREATE_CHECKOUT = "CREATE_CHECKOUT",
  GET_ALL_CHECKOUTS = "GET_ALL_CHECKOUTS",
  GET_CHECKOUT = "GET_CHECKOUT",
  // Review Related
  GET_REVIEW = "GET_REVIEW",
  GET_REVIEWS = "GET_REVIEWS",
}
