import { themeValues } from "@/constants/ThemeConstants";
import { makeStyles } from "@mui/styles";

export const useNavBarStyles = makeStyles((theme) => ({
  navBarRoot: {
    // position: "relative",
    // height: '150vh',
    // backgroundColor: themeValues.color.color2,
  },
  topNavBarRoot: {
    paddingLeft: theme.spacing(1),
    paddingRight: theme.spacing(1),
    paddingTop: theme.spacing(1),
    width: "100vw",
    zIndex: 1,
  },
  libraryName: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    gap: theme.spacing(1.3),
    marginRight: theme.spacing(27),
  },
  topNavBarContainer: {
    backgroundColor: themeValues.color.color1,
    padding: theme.spacing(1.4),
    paddingLeft: theme.spacing(2),
    paddingRight: theme.spacing(2),
    borderRadius: themeValues.border.borderRadius,
    color: themeValues.color.textColor,
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    boxShadow: themeValues.shadow.boxShadowLight,
  },
  searchInputWrap: {
    color: themeValues.color.textColor,
    borderRadius: theme.spacing(0.5),
    backgroundColor: themeValues.color.color2,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    padding: theme.spacing(1),
  },
  searchInput: {
    all: "unset",
    color: themeValues.color.color1,
    outline: themeValues.color.borderColor2,
    backgroundColor: themeValues.color.color2,
    transition: themeValues.transition.defaultTansition,
    caretColor: themeValues.color.transparent,
    "&:hover": {
      boxShadow: themeValues.shadow.boxShadowHeavy,
      cursor: "pointer",
    },
    // "&:focus": {
    //   paddingLeft: theme.spacing(0.5),
    //   paddingRight: theme.spacing(0.5),
    // },
    "&::-webkit-input-placeholder": {
      color: themeValues.color.color1,
      opacity: 1,
    },
  },
  sideNavContainer: {
    position: "sticky",
    top: 0,
    left: 0,
    display: "flex",
    flexDirection: "column",
    // width: themeValues.sideNavWidth,
    minWidth: themeValues.sideNavWidth,
    height: "fit-content",
    // float: "left",
    // minWidth: "max-content",
    gap: theme.spacing(2),
    padding: theme.spacing(1),
    border: themeValues.border.thickborder,
    borderColor: themeValues.color.color3,
    borderTopColor: themeValues.color.transparent,
    borderBottomLeftRadius: themeValues.border.borderRadius,
    borderBottomRightRadius: themeValues.border.borderRadius,
    marginLeft: theme.spacing(1.5),
    transition: themeValues.transition.longTransition,
    overflow: "hidden",
    // boxShadow: themeValues.shadow.boxShadowboxy,
    // animation: "slide-down 1s ease",
  },
  sideMenuItem: {
    color: themeValues.color.color1,
    border: themeValues.border.defaultborder,
    borderColor: themeValues.color.color3,
    borderRadius: themeValues.border.borderRadius,
    display: "flex",
    alignItems: "center",
    justifyContent: "start",
    gap: theme.spacing(2),
    padding: theme.spacing(1),
    fontWeight: themeValues.font.fontWeightThick,
    transition: themeValues.transition.defaultTansition,
    // animation: themeValues.animation.slideUp,
    "&:hover": {
      backgroundColor: themeValues.color.color3,
      color: themeValues.color.textColor,
      boxShadow: themeValues.shadow.boxShadowHeavy,
      cursor: "pointer",
    },
  },
  currentSideMenu: {
    backgroundColor: themeValues.color.color1,
    color: themeValues.color.textColor,
  },
  pageContent: {
    padding: theme.spacing(1),
  },
  settingsMenu: {},
}));
