import { themeValues } from "@/constants/ThemeConstants";
import { makeStyles } from "@mui/styles";

export const useSearchDialogStyles = makeStyles((theme) => ({
  searchDialogContentRoot: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "start",
    padding: theme.spacing(2),
    gap: theme.spacing(1),
    borderRadius: themeValues.border.borderRadius,
    width: "43vw",
    position: "relative",
  },
  searchInputWrap: {
    width: "95%",
    color: themeValues.color.black,
    borderRadius: themeValues.border.borderRadius,
    backgroundColor: themeValues.color.lightGray,
    boxShadow: themeValues.shadow.boxShadowboxy,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    padding: theme.spacing(1),
    marginBottom: theme.spacing(1),
  },
  searchInput: {
    all: "unset",
    width: "100%",
    color: themeValues.color.black,
    outline: themeValues.color.borderColor2,
    backgroundColor: themeValues.color.lightGray,
    transition: themeValues.transition.defaultTansition,
    caretColor: themeValues.color.black,
    paddingLeft: theme.spacing(2),
    paddingRight: theme.spacing(2),
    "&:focus": {},
    "&::-webkit-input-placeholder": {
      color: themeValues.color.black,
      opacity: 1,
    },
  },
  sortByContainer: {
    display: "flex",
    alignSelf: "center",
    gap: theme.spacing(0.5),
  },
  sortByPresence: {
    position: "sticky",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: themeValues.color.lightGray,
    borderRadius: themeValues.border.borderRadius,
    gap: theme.spacing(1),
    padding: theme.spacing(1),
    bottom: theme.spacing(1),
    boxShadow: themeValues.shadow.boxShadowboxy,
    transition: themeValues.transition.defaultTansition,
    userSelect: "none",
    opacity: 0.8,
    "&:hover": {
      opacity: 1,
      boxShadow: themeValues.shadow.boxShadowAttatched,
      cursor: "pointer",
    },
  },
  searchItems: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "start",
    width: "100%",
    marginBottom: theme.spacing(2),
  },
  paginationWrap: {
    zIndex: 1,
    backgroundColor: themeValues.color.white,
    borderRadius: themeValues.border.borderRadiusHigh,
    boxShadow: themeValues.shadow.boxShadowboxy,
    width: "auto",
    position: "sticky",
    bottom: 0,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
}));
