import { themeValues } from "@/constants/ThemeConstants";
import { makeStyles } from "@mui/styles";

export const useTransactionsStyles = makeStyles((theme) => ({
  transactionsRoot: {
    width: "84vw",
    height: "auto",
    display: "flex",
    flexDirection: "column",
    // alignItems: "center",
    justifyContent: "center",
    padding: theme.spacing(2),
    gap: theme.spacing(1),
  },
  sortByContainer: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    maxHeight: theme.spacing(10),
    alignSelf: "center",
    gap: theme.spacing(2),
  },
  searchInputWrap: {
    color: themeValues.color.black,
    borderRadius: themeValues.border.borderRadius,
    backgroundColor: themeValues.color.lightGray,
    boxShadow: themeValues.shadow.boxShadowboxy,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    height: theme.spacing(5),
    paddingLeft: theme.spacing(0.5),
    paddingRight: theme.spacing(0.5),
  },
  searchInput: {
    all: "unset",
    color: themeValues.color.black,
    outline: themeValues.color.borderColor2,
    backgroundColor: themeValues.color.lightGray,
    transition: themeValues.transition.defaultTansition,
    caretColor: themeValues.color.black,
    fontSize: themeValues.font.fontSizeSmall,
    padding: theme.spacing(0),
    paddingLeft: theme.spacing(2),
    paddingRight: theme.spacing(2),
    "&:focus": {},
    "&::-webkit-input-placeholder": {
      fontSize: themeValues.font.fontSizeSmall,
      color: themeValues.color.black,
      opacity: 1,
    },
  },
  accordionActualSummaryRoot: {
    boxShadow: themeValues.shadow.boxShadowboxy,
    // backgroundColor: themeValues.color.lightGray,
    borderRadius: themeValues.border.borderRadius,
  },
  accordionSummaryRoot: {
    width: "97%",
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
  },
  summaryUserAndBook: {
    display: "flex",
    flexDirection: "column",
  },
  summaryFromAndTo: {
    gap: theme.spacing(2),
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  summaryIcon: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    padding: theme.spacing(1),
    border: themeValues.border.defaultborder,
    borderRadius: "50%",
    // backgroundColor: themeValues.color.lightGray,
  },
  detailBoxRoot: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "column",
    gap: theme.spacing(2),
  },
  topDetailBox: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: theme.spacing(3),
  },
  detailsBox: {
    minWidth: "25vw",
    padding: theme.spacing(2),

    color: themeValues.color.black,
    // border: themeValues.border.defaultborder,
    boxShadow: themeValues.shadow.boxShadowboxy,
    // backgroundColor: themeValues.color.lightGray,
    borderRadius: themeValues.border.borderRadius,
  },
  ItemWrap: {
    width: "100%",
    display: "flex",
    alignItems: "center",
    gap: theme.spacing(1),
  },
  ItemKey: {
    width: "50%",
    textAlign: "left",
  },
  ItemValue: {
    width: "50%",
    textAlign: "left",
  },
  dateBoxWrap: {
    width: "60%",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "column",
    gap: theme.spacing(2),
    padding: theme.spacing(2),
    borderRadius: themeValues.border.borderRadius,
    boxShadow: themeValues.shadow.boxShadowboxy,
  },
  dateBox: {
    // backgroundColor: themeValues.color.lightGray,
    width: "40%",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: theme.spacing(2),
  },
  dateKey: {
    width: "50%",
    textAlign: "left",
  },
  dateValue: {
    width: "50%",
    textAlign: "right",
  },
  actionButtonsAccordionDetails: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: theme.spacing(2),
  },
  actionBtn : {
    color: themeValues.color.white,
    backgroundColor: themeValues.color.color1,
    "&:hover": {
      color: themeValues.color.white,
      backgroundColor: themeValues.color.color3,
    },
  },
}));
