import { themeValues } from "@/constants/ThemeConstants";
import { makeStyles } from "@mui/styles";

export const useSingleUserStyles = makeStyles((theme) => ({
  singleUserRoot: {
    width: "85vw",
    height: "auto",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: theme.spacing(3),
    padding: theme.spacing(2),
  },
  userCover: {
    width: "75vw",
    height: "25vh",
    borderRadius: themeValues.border.borderRadiusLow,
    zIndex: 0,
    backgroundColor: themeValues.color.color1,
  },
  userImageWrap: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    width: "10vw",
    height: "20vh",
    position: "relative",
    left: -25,
    top: 40,
    zIndex: 1,
    boxShadow: themeValues.shadow.boxShadowHeavy,
    borderRadius: themeValues.border.borderRadiusLow,
    backgroundColor: themeValues.color.color2,
  },
  userImage: {
    width: "10vw",
    height: "20vh",
    objectFit: "cover",
    opacity: 0.8,
    borderRadius: themeValues.border.borderRadiusLow,
  },
  userDetailsContainer: {
    width: "20vw",
    height: "25vh",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    boxShadow: themeValues.shadow.boxShadowLight,
    borderRadius: themeValues.border.borderRadiusHigh,
    // backgroundColor: "red",
  },
  userDetailBox: {
    width: "100%",
    display: "flex",
    justifyContent: "space-between",
    gap: theme.spacing(4),
    padding: theme.spacing(1.5),
  },
  userDetailKey: {
    width: "50%",
    fontWeight: themeValues.font.fontWeightLightThick,
    fontSize: themeValues.spacing(2),
    display: "flex",
    alignItems: "center",
    justifyContent: "end",
    alignSelf: "start",
    textAlign: "right",
  },
  userDetailValue: {
    display: "flex",
    alignItems: "center",
    justifyContent: "start",
    fontSize: themeValues.spacing(1.9),
    width: "50%",
    textAlign: "left",
  },
  bookDetailsContainer: {
    width: "80vw",
    height: "25vh",
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: theme.spacing(3),
  },
  bookDetailBox: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    alignSelf: "center",
    gap: theme.spacing(2),
    padding: theme.spacing(2),
    borderRadius: themeValues.border.borderRadiusHigh,
    transition: themeValues.transition.defaultTansition,
    boxShadow: themeValues.shadow.boxShadowboxy,
    color: themeValues.color.color1,
    "&:hover": {
      backgroundColor: themeValues.color.color1,
      color: themeValues.color.textColor,
      boxShadow: themeValues.shadow.boxShadowHeavy,
      cursor: "pointer",
    },
  },
  bookDetailKey: {
    fontWeight: themeValues.font.fontWeightLightThick,
    fontSize: themeValues.spacing(2),
    alignSelf: "start",
  },
  bookDetailValue: {},
}));
