name: ILM-Frontend

on:
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js and Yarn
        uses: actions/setup-node@v3
        with:
          node-version: 14
          registry-url: https://registry.yarnpkg.com/

      - name: Install Dependencies
        run: yarn install

      - name: Lint
        run: yarn lint

      - name: Well Formatted
        run: yarn format:check

      - name: Type Check
        run: yarn type-check

      - name: Build
        run: yarn build
